# Site settings
title: zaran.me
email: lalvaz@rpi.edu
description: > # this means to ignore newlines until "baseurl:"
  Zaran Lalvani's personal website. 
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://zaran.me" # the base hostname & protocol for your site
twitter_username: none
github_username:  zlalvani

sass:
  # loading path from site root
  # default to _sass
  #sass_dir: bower_components/bootstrap-sass/assets/stylesheets

  # style : nested (default), compact, compressed, expanded
  #         :nested, :compact, :compressed, :expanded also works
  # see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style
  # on a typical twitter bootstrap stats are :
  # nested 138,7kB, compact 129,1kB, expanded 135,9 kB, compressed 122,4 kB
  style: compressed

# Build settings
markdown: kramdown
